### ISSUE TITLE
Allow user to specify their GitHub username

### ISSUE THREAD

**Issue by NStefan002** [only-mar/Github-Readme-Generator#1]
Hi! Very nice project! I only took a quick look, so I may have missed it, but is there a way to input your gh username? I tried to enter it in the `Name` field but that only changes the title of the readme, and the `username` field in stats remains `johndoe`.  For people who haven't used gh stats before, it may take some time to figure it out.

Edit: I realized (when I went through code) that you need to set the first link in `Social`, to your GitHub page. Can you indicate that somehow, or move it to separate input, like `Name`?

**Comment by n0tmar** [comment]
Hey @NStefan002! Thanks a lot for checking out the project and sharing your feedback! 😊

You were right, the GitHub username being a bit tricky to find. I've just updated the website to make this more user-friendly:

**- Now there's a nice and clear `GitHub username` field right at the top of the form**
**- It only shows up when you're using templates that need it and it's automatically syncs with the GitHub URL**

I really appreciate you bringing this up - it's going to make the experience much better for everyone!

Could you please give it another try and let me know what you think 🤔? 

![image](https://github.com/user-attachments/assets/ed7faf13-1b67-47c9-b94d-b8e19ef5b3b9)

**Comment by NStefan002** [comment]
Thanks for the quick response! The updated version is very nice, thank you!
